import { StatusBadge } from "@/components/portal/status-badge";
import { prisma } from "@/lib/db";
import { requireAdmin } from "@/modules/auth/guards";
import { retryContactNotificationAction, updateContactStatusAction } from "@/modules/contact/admin-actions";

export default async function ContactsPage() {
  await requireAdmin();
  const contacts = await prisma.contactSubmission.findMany({ orderBy: { createdAt: "desc" }, take: 100 });
  return <div className="workspace-page"><header className="workspace-heading"><div><p className="sv-eyebrow">Pipeline de contacto</p><h1>Contextos recibidos.</h1></div><p>La recepción persistida y la notificación por correo se muestran como estados independientes.</p></header><section className="workspace-panel"><div className="data-list">{contacts.length ? contacts.map((contact) => <article key={contact.id} className="data-list__expanded"><div><strong>{contact.name}</strong><p>{[contact.organization, contact.role].filter(Boolean).join(" · ") || "Sin organización ni rol informados"}</p><a href={`mailto:${contact.email}`}>{contact.email}</a><p className="data-list__body">{contact.context}</p></div><div><StatusBadge value={contact.status} /><span>Notificación: {contact.notificationStatus}</span><span>Intentos: {contact.notificationAttempts}</span>{contact.notificationLastErrorCode ? <span>Error: {contact.notificationLastErrorCode}</span> : null}<time>{contact.createdAt.toLocaleDateString("es-EC")}</time><form action={updateContactStatusAction.bind(null, contact.id)}><select name="status" defaultValue={contact.status}>{["NEW", "REVIEWED", "ARCHIVED"].map((status) => <option value={status} key={status}>{status}</option>)}</select><button type="submit">Guardar</button></form>{contact.notificationStatus === "FAILED" ? <form action={retryContactNotificationAction.bind(null, contact.id)}><button type="submit">Reintentar notificación</button></form> : null}</div></article>) : <p className="empty-state">No hay contactos registrados.</p>}</div></section></div>;
}
