import { notFound } from "next/navigation";
import { StatusBadge } from "@/components/portal/status-badge";
import { DocumentUploadForm } from "@/components/portal/document-upload-form";
import { Button } from "@/components/ui/button";
import { prisma } from "@/lib/db";
import { requireInternalProjectAccess } from "@/modules/auth/guards";
import { createInvoiceAction } from "@/modules/projects/billing-actions";
import { addDeliverableAction, addMilestoneAction, addPhaseAction, createDocumentAction, inviteClientAction, publishProjectAction, retryClientInvitationAction, updateDocumentStateAction, updateProjectAction } from "@/modules/projects/admin-actions";

export default async function AdminProjectPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ invite?: string }> }) {
  const { id } = await params;
  const { invite } = await searchParams;
  await requireInternalProjectAccess(id);
  const [project, managers] = await Promise.all([
    prisma.project.findUnique({
      where: { id },
      include: {
      organization: { include: { contacts: { orderBy: { name: "asc" } } } },
      primaryContact: true,
      internal: { include: { projectManager: { select: { id: true, name: true, email: true } } } },
      phases: { orderBy: { position: "asc" } },
      milestones: { orderBy: { position: "asc" } },
      deliverables: { orderBy: { createdAt: "asc" }, include: { documents: { orderBy: { createdAt: "asc" }, include: { versions: { orderBy: { version: "desc" }, include: { file: true } } } } } },
      memberships: { include: { user: { select: { id: true, name: true, email: true } } } },
      invitations: { orderBy: { createdAt: "desc" } },
      audits: { where: { action: "CLIENT_INVITATION_SEND_FAILED" }, select: { targetId: true } },
      publications: { orderBy: { version: "desc" }, take: 10 },
      invoices: { orderBy: { createdAt: "desc" } },
      },
    }),
    prisma.user.findMany({ where: { kind: "INTERNAL", disabledAt: null }, orderBy: { name: "asc" }, select: { id: true, name: true, email: true } }),
  ]);
  if (!project) notFound();

  return (
    <div className="workspace-page">
      <header className="workspace-heading"><div><p className="sv-eyebrow">{project.organization.name}</p><h1>{project.name}</h1></div><div className="heading-status"><StatusBadge value={project.status} /><span>Última publicación: v{project.publications.find((item) => item.status === "PUBLISHED")?.version ?? "—"}</span></div></header>

      {invite ? <div className={`notice ${invite === "sent" ? "notice--success" : "notice--warning"}`} role={invite === "sent" ? "status" : "alert"}>{invite === "sent" ? "Invitación enviada y registrada." : invite === "failed" ? "El correo no pudo entregarse. El token fue revocado y el acceso sigue pendiente; puedes reintentar." : "El correo de invitación no está configurado. No se creó ningún acceso ni token."}</div> : null}

      <section className="workspace-panel"><div className="panel-heading"><h2>Resumen interno</h2><p>Guardar no publica.</p></div><form action={updateProjectAction.bind(null, id)} className="workspace-form"><div className="form-grid"><div className="field"><label htmlFor="name">Nombre</label><input id="name" name="name" defaultValue={project.name} required /></div><div className="field"><label htmlFor="status">Estado</label><select id="status" name="status" defaultValue={project.status}>{["DISCOVERY", "ACTIVE", "PAUSED", "COMPLETED", "ARCHIVED"].map((status) => <option key={status} value={status}>{status}</option>)}</select></div><div className="field"><label htmlFor="reference">Referencia</label><input id="reference" name="reference" defaultValue={project.reference ?? ""} maxLength={120} /></div><div className="field"><label htmlFor="projectManagerId">Responsable SyntaVera</label><select id="projectManagerId" name="projectManagerId" defaultValue={project.internal?.projectManagerId ?? ""} required>{managers.map((manager) => <option key={manager.id} value={manager.id}>{manager.name} · {manager.email}</option>)}</select></div><div className="field field--full"><label htmlFor="primaryContactId">Contacto principal</label><select id="primaryContactId" name="primaryContactId" defaultValue={project.primaryContactId ?? ""}><option value="">Sin contacto principal</option>{project.organization.contacts.map((contact) => <option key={contact.id} value={contact.id}>{contact.name} · {contact.email}</option>)}</select></div><div className="field field--full"><label htmlFor="objective">Objetivo</label><textarea id="objective" name="objective" defaultValue={project.objective} minLength={20} required /></div><div className="field field--full"><label htmlFor="summary">Resumen publicable</label><textarea id="summary" name="summary" defaultValue={project.summary} minLength={20} required /></div></div><Button type="submit">Guardar borrador</Button></form></section>

      <section className="workspace-grid-3">
        <form action={addPhaseAction.bind(null, id)} className="workspace-panel workspace-form"><div className="panel-heading"><h2>Nueva fase</h2><p>Ordenada al final.</p></div><div className="field"><label htmlFor="phase-name">Nombre</label><input id="phase-name" name="name" required /></div><div className="field"><label htmlFor="clientSummary">Resumen cliente</label><textarea id="clientSummary" name="clientSummary" /></div><Button type="submit" variant="secondary">Añadir fase</Button></form>
        <form action={addMilestoneAction.bind(null, id)} className="workspace-panel workspace-form"><div className="panel-heading"><h2>Nuevo hito</h2><p>Puede vincularse a una fase.</p></div><div className="field"><label htmlFor="milestone-title">Título</label><input id="milestone-title" name="title" required /></div><div className="field"><label htmlFor="phaseId">Fase</label><select id="phaseId" name="phaseId"><option value="">Sin fase</option>{project.phases.map((phase) => <option value={phase.id} key={phase.id}>{phase.name}</option>)}</select></div><input type="hidden" name="description" value="" /><Button type="submit" variant="secondary">Añadir hito</Button></form>
        <form action={addDeliverableAction.bind(null, id)} className="workspace-panel workspace-form"><div className="panel-heading"><h2>Nuevo entregable</h2><p>Se crea en revisión.</p></div><div className="field"><label htmlFor="deliverable-title">Título</label><input id="deliverable-title" name="title" required /></div><div className="field"><label htmlFor="milestoneId">Hito</label><select id="milestoneId" name="milestoneId"><option value="">Sin hito</option>{project.milestones.map((milestone) => <option value={milestone.id} key={milestone.id}>{milestone.title}</option>)}</select></div><input type="hidden" name="description" value="" /><Button type="submit" variant="secondary">Añadir entregable</Button></form>
      </section>

      <section className="workspace-panel"><div className="panel-heading"><h2>Plan y entregables</h2><p>Fuente relacional. Solo los elementos publicables entran al snapshot.</p></div><div className="data-list">{project.phases.map((phase) => <article key={phase.id}><div><strong>{String(phase.position + 1).padStart(2, "0")} · {phase.name}</strong><p>{phase.clientSummary ?? "Sin resumen cliente"}</p></div><StatusBadge value={phase.status} /></article>)}{project.deliverables.map((item) => <article key={item.id}><div><strong>{item.title}</strong><p>{item.documents.length} documentos · {item.documents.reduce((count, document) => count + document.versions.length, 0)} versiones</p></div><StatusBadge value={item.status} /></article>)}</div></section>

      <section className="workspace-grid-2"><form action={createDocumentAction.bind(null, id)} className="workspace-panel workspace-form"><div className="panel-heading"><h2>Nuevo documento</h2><p>Nace como borrador y no entra al snapshot.</p></div><div className="field"><label htmlFor="document-title">Título</label><input id="document-title" name="title" required /></div><div className="field"><label htmlFor="document-deliverable">Entregable</label><select id="document-deliverable" name="deliverableId" required><option value="">Selecciona</option>{project.deliverables.map((deliverable) => <option value={deliverable.id} key={deliverable.id}>{deliverable.title}</option>)}</select></div><Button type="submit" variant="secondary">Crear documento</Button></form><div className="workspace-panel"><div className="panel-heading"><h2>Documentos y versiones</h2><p>R2 se confirma antes de persistir metadata.</p></div><div className="document-admin-list">{project.deliverables.flatMap((deliverable) => deliverable.documents.map((document) => <article className="document-admin-card" key={document.id}><div><strong>{document.title}</strong><p>{deliverable.title} · {document.versions.length} versiones</p><StatusBadge value={document.state} /></div><form action={updateDocumentStateAction.bind(null, id, document.id)}><label htmlFor={`document-state-${document.id}`}>Estado</label><select id={`document-state-${document.id}`} name="state" defaultValue={document.state}><option value="DRAFT">Borrador</option><option value="PUBLISHED">Publicado</option><option value="ARCHIVED">Archivado</option></select><button type="submit">Guardar</button></form><DocumentUploadForm projectId={id} documentId={document.id} /></article>))}{project.deliverables.every((deliverable) => !deliverable.documents.length) ? <p className="empty-state">No hay documentos.</p> : null}</div></div></section>

      <section className="workspace-grid-2" id="client-access">
        <form action={inviteClientAction.bind(null, id)} className="workspace-panel workspace-form"><div className="panel-heading"><h2>Invitar cliente</h2><p>La invitación y el acceso son de un solo uso.</p></div><div className="field"><label htmlFor="client-name">Nombre</label><input id="client-name" name="name" required /></div><div className="field"><label htmlFor="client-email">Email</label><input id="client-email" name="email" type="email" required /></div><fieldset className="permission-field"><legend>Permisos</legend>{["VIEW", "COMMENT", "APPROVE", "FINANCE"].map((permission) => <label key={permission}><input type="checkbox" name="permissions" value={permission} defaultChecked={permission === "VIEW"} /> {permission}</label>)}</fieldset><Button type="submit">Enviar invitación</Button></form>
        <div className="workspace-panel"><div className="panel-heading"><h2>Accesos</h2><p>Estado real de cada acceso e invitación.</p></div><div className="data-list">{project.memberships.length ? project.memberships.map((membership) => {
          const invitation = project.invitations.find((item) => item.email === membership.user.email);
          const failed = Boolean(invitation && project.audits.some((audit) => audit.targetId === invitation.id));
          const state = membership.status === "ACTIVE" ? "Activo" : membership.status === "REVOKED" ? "Revocado" : failed ? "Envío fallido" : invitation?.revokedAt ? "Revocado" : invitation && invitation.expiresAt <= new Date() ? "Expirado" : invitation ? "Invitación enviada" : "Pendiente sin envío";
          return <article key={membership.id}><div><strong>{membership.user.name}</strong><p>{membership.user.email}</p><span>{state}</span></div><div><StatusBadge value={membership.status} /><span>{membership.permissions.join(" · ")}</span>{membership.status === "INVITED" ? <form action={retryClientInvitationAction.bind(null, id, membership.user.id)}><Button type="submit" variant="secondary" size="sm">Reintentar invitación</Button></form> : null}</div></article>;
        }) : <p className="empty-state">No hay personas cliente invitadas.</p>}</div></div>
      </section>

      <section className="workspace-grid-2">
        <form action={createInvoiceAction.bind(null, id)} className="workspace-panel workspace-form"><div className="panel-heading"><h2>Metadatos de factura</h2><p>El cobro ocurre en el sistema externo.</p></div><div className="form-grid"><div className="field"><label htmlFor="number">Número</label><input id="number" name="number" required /></div><div className="field"><label htmlFor="totalMinor">Total (centavos)</label><input id="totalMinor" name="totalMinor" type="number" min="0" required /></div><div className="field"><label htmlFor="currency">Moneda</label><input id="currency" name="currency" defaultValue="USD" maxLength={3} required /></div><div className="field"><label htmlFor="externalId">ID externo</label><input id="externalId" name="externalId" /></div><div className="field field--full"><label htmlFor="externalUrl">URL externa</label><input id="externalUrl" name="externalUrl" type="url" /></div><div className="field"><label htmlFor="documentState">Documento</label><select id="documentState" name="documentState" defaultValue="DRAFT"><option>DRAFT</option><option>ISSUED</option><option>VOID</option></select></div><div className="field"><label htmlFor="paymentState">Pago</label><select id="paymentState" name="paymentState" defaultValue="UNPAID"><option>UNPAID</option><option>PARTIALLY_PAID</option><option>PAID</option><option>OVERDUE</option><option>REFUNDED</option></select></div></div><Button type="submit" variant="secondary">Guardar factura</Button></form>
        <div className="workspace-panel"><div className="panel-heading"><h2>Facturación</h2><p>Estados documental y de pago separados.</p></div><div className="data-list">{project.invoices.length ? project.invoices.map((invoice) => <article key={invoice.id}><div><strong>{invoice.number}</strong><p>{new Intl.NumberFormat("es-EC", { style: "currency", currency: invoice.currency }).format(invoice.totalMinor / 100)}</p></div><div><StatusBadge value={invoice.documentState} /><StatusBadge value={invoice.paymentState} /></div></article>) : <p className="empty-state">Sin facturas.</p>}</div></div>
      </section>

      <section className="publish-panel"><div><p className="sv-eyebrow">Gate de publicación</p><h2>Crear snapshot cliente.</h2><p>Solo los campos seleccionados se copian. Notas internas, claves de almacenamiento y mensajes internos quedan fuera.</p></div><form action={publishProjectAction.bind(null, id)} className="workspace-form"><div className="field"><label htmlFor="changeSummary">Resumen de cambios</label><textarea id="changeSummary" name="changeSummary" minLength={4} maxLength={500} required /></div><Button type="submit" size="lg">Publicar revisión</Button></form></section>
    </div>
  );
}
