import { notFound } from "next/navigation";
import { StatusBadge } from "@/components/portal/status-badge";
import { Button } from "@/components/ui/button";
import { prisma } from "@/lib/db";
import { requireInternalProjectAccess } from "@/modules/auth/guards";
import { replyToTicketAction, updateTicketStatusAction } from "@/modules/support/admin-actions";

export default async function AdminTicketPage({ params }: { params: Promise<{ ticketId: string }> }) {
  const { ticketId } = await params;
  const ticket = await prisma.ticket.findUnique({ where: { id: ticketId }, include: { project: true, messages: { orderBy: { createdAt: "asc" }, include: { author: { select: { name: true } } } } } });
  if (!ticket) notFound();
  await requireInternalProjectAccess(ticket.projectId);
  return <div className="workspace-page workspace-page--narrow"><header className="workspace-heading"><div><p className="sv-eyebrow">{ticket.project.name}</p><h1>{ticket.subject}</h1></div><div className="heading-status"><StatusBadge value={ticket.priority} /><StatusBadge value={ticket.status} /></div></header><section className="message-thread">{ticket.messages.map((message) => <article className={message.visibility === "INTERNAL" ? "message message--internal" : "message"} key={message.id}><div><strong>{message.author.name}</strong><StatusBadge value={message.visibility} /></div><p>{message.body}</p><time>{message.createdAt.toLocaleString("es-EC")}</time></article>)}</section><section className="workspace-grid-2"><form action={replyToTicketAction.bind(null, ticketId)} className="workspace-panel workspace-form"><div className="panel-heading"><h2>Responder</h2><p>Elige explícitamente la visibilidad.</p></div><div className="field"><label htmlFor="body">Mensaje</label><textarea id="body" name="body" required /></div><div className="field"><label htmlFor="visibility">Visibilidad</label><select id="visibility" name="visibility"><option value="CLIENT">Cliente</option><option value="INTERNAL">Solo interno</option></select></div><Button type="submit">Guardar mensaje</Button></form><form action={updateTicketStatusAction.bind(null, ticketId)} className="workspace-panel workspace-form"><div className="panel-heading"><h2>Estado y prioridad</h2><p>Los cambios aparecen en Actividad.</p></div><div className="field"><label htmlFor="status">Estado</label><select id="status" name="status" defaultValue={ticket.status}>{["OPEN", "IN_PROGRESS", "WAITING_CLIENT", "RESOLVED", "CLOSED"].map((status) => <option value={status} key={status}>{status}</option>)}</select></div><div className="field"><label htmlFor="priority">Prioridad</label><select id="priority" name="priority" defaultValue={ticket.priority}>{["LOW", "NORMAL", "HIGH", "CRITICAL"].map((priority) => <option value={priority} key={priority}>{priority}</option>)}</select></div><label className="checkbox-field"><input type="checkbox" name="criticalConfirmed" /> <span>Confirmo el uso de prioridad crítica para un bloqueo inmediato.</span></label><Button type="submit" variant="secondary">Actualizar ticket</Button></form></section></div>;
}
