import Link from "next/link";
import { Button } from "@/components/ui/button";
import { prisma } from "@/lib/db";
import { requireInternalUser } from "@/modules/auth/guards";
import { createProjectAction } from "@/modules/projects/admin-actions";

export default async function NewProjectPage() {
  const { user } = await requireInternalUser();
  const [organizations, managers] = await Promise.all([
    prisma.organization.findMany({ orderBy: { name: "asc" }, include: { contacts: { orderBy: { name: "asc" } } } }),
    prisma.user.findMany({ where: { kind: "INTERNAL", disabledAt: null }, orderBy: { name: "asc" }, select: { id: true, name: true, email: true } }),
  ]);
  if (!organizations.length) return <div className="workspace-page workspace-page--narrow"><header className="workspace-heading"><div><p className="sv-eyebrow">Nuevo proyecto</p><h1>Primero crea una organización.</h1></div></header><section className="workspace-panel"><p>Los proyectos siempre pertenecen a una organización real.</p><Link href="/admin/organizations">Abrir organizaciones</Link></section></div>;
  return <div className="workspace-page workspace-page--narrow"><header className="workspace-heading"><div><p className="sv-eyebrow">Nuevo proyecto</p><h1>Crea la fuente interna.</h1></div><p>El portal seguirá vacío hasta una publicación explícita.</p></header><form action={createProjectAction} className="workspace-panel workspace-form"><div className="form-grid"><div className="field"><label htmlFor="organizationId">Organización</label><select id="organizationId" name="organizationId" required>{organizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select></div><div className="field"><label htmlFor="projectManagerId">Responsable SyntaVera</label><select id="projectManagerId" name="projectManagerId" defaultValue={user.id} required>{managers.map((manager) => <option key={manager.id} value={manager.id}>{manager.name} · {manager.email}</option>)}</select></div><div className="field"><label htmlFor="name">Proyecto</label><input id="name" name="name" required /></div><div className="field"><label htmlFor="projectSlug">Slug proyecto</label><input id="projectSlug" name="projectSlug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></div><div className="field"><label htmlFor="status">Etapa</label><select id="status" name="status" defaultValue="DISCOVERY"><option value="DISCOVERY">Descubrimiento</option><option value="ACTIVE">Ejecución</option><option value="PAUSED">Pausado</option><option value="COMPLETED">Cerrado</option></select></div><div className="field"><label htmlFor="reference">Referencia</label><input id="reference" name="reference" maxLength={120} /></div><div className="field field--full"><label htmlFor="primaryContactId">Contacto principal</label><select id="primaryContactId" name="primaryContactId" defaultValue=""><option value="">Sin contacto principal</option>{organizations.flatMap((organization) => organization.contacts.map((contact) => <option key={contact.id} value={contact.id}>{organization.name} · {contact.name} · {contact.email}</option>))}</select><small>El servidor verifica que el contacto pertenezca a la organización elegida.</small></div><div className="field field--full"><label htmlFor="objective">Objetivo</label><textarea id="objective" name="objective" minLength={20} required /></div><div className="field field--full"><label htmlFor="summary">Texto inicial de estado</label><textarea id="summary" name="summary" minLength={20} required /></div></div><Button type="submit">Crear proyecto</Button></form></div>;
}
